version: "1"
services:
  db:
    build: ./database
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - "./db_data:/var/lib/mysql:rw"

  backend:
    build: ./backend
    ports:
      - "1144:1144"

  web:
    build: ./frontend
    ports:
      - "5173:5173"